# Generated by Django 4.2.16 on 2024-10-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
