# Generated by Django 4.2.16 on 2024-10-05 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="created_at",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="trip_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
