# Generated by Django 4.2.16 on 2024-10-06 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_blogpost_created_at_blogpost_trip_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="trip_date",
            new_name="event_date",
        ),
        migrations.RenameField(
            model_name="blogpost",
            old_name="image",
            new_name="head_image",
        ),
        migrations.CreateModel(
            name="BlogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog_images/")),
                (
                    "blog_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_images",
                        to="blog.blogpost",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blogpost",
            name="other_images",
            field=models.ManyToManyField(blank=True, to="blog.blogimage"),
        ),
    ]
